language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
env:
  global:
    - MONGODB=2.6.11
    - CASSANDRA_VERSION=3.11.4
  matrix:
    - SUITE=versioned
services:
  - memcached
  - mysql
  - redis
  - postgresql
  - rabbitmq
addons:
  apt:
    packages:
    - rabbitmq-server
before_install:
  - ./bin/travis-setup.sh
install: if [ "$SUITE" != "smoke" ]; then npm ci; fi
cache:
  directories:
    - "$HOME/.npm"
script: npm run $SUITE
